language: go
sudo: false
go_import_path: github.com/go-session/beego-session
go:
  - 1.9
before_install:
  - go get github.com/mattn/goveralls
script:
  - $HOME/gopath/bin/goveralls -service=travis-ci
